import { Scenario } from '../../types/scenario'

/** 1장 — 운명적 만남 (유메 구출 → 일상 → 장비 이상 → Dr. 제로) */
export const CH1_SCENARIO: Scenario = {
  id: 'ch1',
  title: 'CHAPTER 1',
  subtitle: '운명적 만남',
  startNodeId: 'open',
  nodes: {
    // ── Act 1: 유메 구출 ──
    open: {
      id: 'open',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '북쪽 시장 폐허. 녹슨 간판과 부서진 유리.\n엘라는 렌의 신호에 맞춰 조용히 전진했다.',
      nextNodeId: 'ren_whisper',
    },
    ren_whisper: {
      id: 'ren_whisper',
      type: 'dialogue',
      speakerId: 'ren',
      text: '수색대 두 명. 우회해서 들어가. 3분 뒤 합류.',
      nextNodeId: 'ella_nod',
    },
    ella_nod: {
      id: 'ella_nod',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……알겠어.',
      nextNodeId: 'yume_chase',
    },
    yume_chase: {
      id: 'yume_chase',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '골목 저편에서 발소리. 작은 체구의 소녀가 세력군에게 쫓기고 있었다.',
      nextNodeId: 'yume_panic',
    },
    yume_panic: {
      id: 'yume_panic',
      type: 'dialogue',
      speakerId: 'yume',
      text: '잠깐——! 제발, 저리——!',
      nextNodeId: 'soldier_ch1',
    },
    soldier_ch1: {
      id: 'soldier_ch1',
      type: 'dialogue',
      speakerId: 'soldier',
      text: '미등록 빈민. 확보한다.',
      nextNodeId: 'ella_act',
      effects: { emotion: { anger: 5 } },
    },
    ella_act: {
      id: 'ella_act',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '엘라는 생각하기 전에 몸이 움직였다.\n파이프를 밟고, 벽을 차고, 쓰러진 간판 아래로 소녀를 끌어당겼다.',
      nextNodeId: 'ella_pull',
    },
    ella_pull: {
      id: 'ella_pull',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……숨 쉬지 마. 움직이지 마.',
      nextNodeId: 'yume_shock',
    },
    yume_shock: {
      id: 'yume_shock',
      type: 'dialogue',
      speakerId: 'yume',
      text: '……! 너, 방금——',
      nextNodeId: 'ren_cover',
    },
    ren_cover: {
      id: 'ren_cover',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '멀리서 유인탄 소리. 렌이 수색병의 시선을 끌었다.\n몇 분 후, 골목은 다시 고요해졌다.',
      nextNodeId: 'yume_thanks',
      effects: { flags: { met_yume: true } },
    },
    yume_thanks: {
      id: 'yume_thanks',
      type: 'dialogue',
      speakerId: 'yume',
      text: '고, 고마워……! 정말, 정말 고마워!\n이름이 뭐야? 아—— 나는 유메!',
      nextNodeId: 'ella_awkward',
      effects: { emotion: { joy: 5, affectionYume: 5 } },
    },
    ella_awkward: {
      id: 'ella_awkward',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……엘라. \n……별로, 대단한 건 아니야.',
      nextNodeId: 'yume_admire',
    },
    yume_admire: {
      id: 'yume_admire',
      type: 'dialogue',
      speakerId: 'yume',
      text: '아니야, 대단해! 저렇게 움직이는 사람, 처음 봤어!\n……혹시, 같이 갈 수 있을까? 혼자는, 무서워서……',
      nextNodeId: 'ren_return',
    },
    ren_return: {
      id: 'ren_return',
      type: 'dialogue',
      speakerId: 'ren',
      text: '……무슨 일이야. 소란스럽군.',
      nextNodeId: 'intro_ren',
    },
    intro_ren: {
      id: 'intro_ren',
      type: 'dialogue',
      speakerId: 'yume',
      text: '저, 이 분이—— 엘라 씨가 저를 구해줬어요!\n렌…… 씨, 맞죠? 엘라 씨가 말해줬어요.',
      nextNodeId: 'ren_assess',
    },
    ren_assess: {
      id: 'ren_assess',
      type: 'dialogue',
      speakerId: 'ren',
      text: '……또 입양한 건 아니겠지.\n일단은 따라와. 단, 규칙을 어기면 바로 내보낸다.',
      nextNodeId: 'ella_ren',
    },
    ella_ren: {
      id: 'ella_ren',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……나는 그냥, 지나가던 사람이었을 뿐이야.',
      nextNodeId: 'yume_stay',
    },
    yume_stay: {
      id: 'yume_stay',
      type: 'dialogue',
      speakerId: 'yume',
      text: '지나가던 사람이 그렇게 구해주진 않잖아!\n……엘라 씨 옆에 있으면, 뭔가 안심돼.',
      nextNodeId: 'act2_montage',
      effects: { emotion: { affectionYume: 8 } },
    },

    // ── Act 2: 함께하는 시간 ──
    act2_montage: {
      id: 'act2_montage',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '——\n\n유메는 은신처에 남았다.\n며칠이 지나고, 몇 주가 지났다.',
      nextNodeId: 'yume_map',
    },
    yume_map: {
      id: 'yume_map',
      type: 'dialogue',
      speakerId: 'yume',
      text: '엘라 씨, 이쪽은 수색대 순찰 간격이 12분이야. 여기서 우회하면 안전해.\n……내가 밤새 경로 정리해뒀어!',
      nextNodeId: 'ella_map',
    },
    ella_map: {
      id: 'ella_map',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……고마워. 나보다, 머리가 빠르네.',
      nextNodeId: 'yume_want_help',
    },
    yume_want_help: {
      id: 'yume_want_help',
      type: 'dialogue',
      speakerId: 'yume',
      text: '힘은 약해도, 도움이 되고 싶어.\n엘라 씨만큼은 못 되지만—— 뭔가, 같이 하고 싶어.',
      nextNodeId: 'yume_cook',
    },
    yume_cook: {
      id: 'yume_cook',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '유메는 합성 영양블록을 억지로 요리해 냈고, 결과는 늘 비재촉물이었다.\n그래도 엘라는 조용히 다 먹었다.',
      nextNodeId: 'ella_eat',
      effects: { emotion: { joy: 8, affectionYume: 10 } },
    },
    ella_eat: {
      id: 'ella_eat',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……맛은 모르겠는데. 배는 불러.\n……고마워, 유메.',
      nextNodeId: 'yume_blush',
    },
    yume_blush: {
      id: 'yume_blush',
      type: 'dialogue',
      speakerId: 'yume',
      text: '엘라 씨가 고마워한다고? ……그, 그럼 또 만들어줄게!\n(……엘라 씨, 웃은 것 같기도 하고. 기분 탓이겠지.)',
      nextNodeId: 'ren_watch',
    },
    ren_watch: {
      id: 'ren_watch',
      type: 'dialogue',
      speakerId: 'ren',
      text: '……분위기는 좋아 보이는군.\n하지만 밖은 여전히 위험해. 방심하지 마.',
      nextNodeId: 'hardship',
    },
    hardship: {
      id: 'hardship',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '수색대의 습격, 식량 부족, 장비 고장—— 작은 고난은 이어졌지만, 셋은 버텼다.\n유메의 전술과 엘라의 피지컬, 렌의 경험이 맞물리며.',
      nextNodeId: 'act3_combat',
      effects: { emotion: { sadness: 5, affectionYume: 5 } },
    },

    // ── Act 3: 장비 이상 ──
    act3_combat: {
      id: 'act3_combat',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '【순찰 교전】\n폐허 외곽. 세력군 드론 두 대와 마주쳤을 때——',
      nextNodeId: 'ella_fight',
    },
    ella_fight: {
      id: 'ella_fight',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……닥치지 않아. \n——이, 뭐야.',
      nextNodeId: 'system_sync',
    },
    system_sync: {
      id: 'system_sync',
      type: 'dialogue',
      speakerId: 'system',
      text: '[장비] Emotion Sync 10%……\n[장비] 감정 연산 자원, 1차 할당.',
      nextNodeId: 'narrator_blast',
      effects: { flags: { emotion_sync_unlocked: true }, emotion: { anger: 10 }, syncPercent: 10 },
    },
    narrator_blast: {
      id: 'narrator_blast',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '엘라의 팔에서 창백한 빛이 퍼졌다. 드론은 순식간에 무너졌고, 골목은 잿더미만 남았다.\n유메와 렌은 말없이 엘라를 바라보았다.',
      nextNodeId: 'yume_worry',
    },
    yume_worry: {
      id: 'yume_worry',
      type: 'dialogue',
      speakerId: 'yume',
      text: '엘라 씨……! 괜찮아? \n저 장비, 방금—— 보급형이 맞아?',
      nextNodeId: 'ella_confused',
    },
    ella_confused: {
      id: 'ella_confused',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……모르겠어. 몸이, 먼저—— \n……평범한 장비가 아닌 것 같아.',
      nextNodeId: 'yume_research',
    },
    yume_research: {
      id: 'yume_research',
      type: 'dialogue',
      speakerId: 'yume',
      text: '조금만 시간을 줘. 기록을 모아볼게.\n음지 네트워크에—— 혹시 이걸 아는 사람이 있을지도.',
      nextNodeId: 'yume_network',
    },
    yume_network: {
      id: 'yume_network',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '유메는 밤마다 낡은 단말기를 두드렸다.\n암호화된 채널, 버려진 서버, 이름 없는 ID들——',
      nextNodeId: 'yume_contact',
    },
    yume_contact: {
      id: 'yume_contact',
      type: 'dialogue',
      speakerId: 'yume',
      text: '……왔어! 답장이!\n「Dr. 제로」—— 장비 해석 전문가래. 거의 세상에 안 드러나는 사람이지만.',
      nextNodeId: 'ren_zero',
    },
    ren_zero: {
      id: 'ren_zero',
      type: 'dialogue',
      speakerId: 'ren',
      text: '……그 이름은 알아. 위험한 사람이지.\n하지만, 지금은 선택지가 없군.',
      nextNodeId: 'act4_zero',
    },

    // ── Act 4: Dr. 제로 ──
    act4_zero: {
      id: 'act4_zero',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '아스포델 최하층. 누수되는 배관과 네온 없는 복도.\n유메가 받은 좌표 끝에, 작은 연구실 문이 있었다.',
      nextNodeId: 'zero_greet',
    },
    zero_greet: {
      id: 'zero_greet',
      type: 'dialogue',
      speakerId: 'zero',
      text: '어서 와. ……오, 이건 뭐야.\n보급형이라기엔, 감정 스펙트럼이 너무 예쁘게 나오는데?',
      nextNodeId: 'ella_cold',
      effects: { flags: { met_dr_zero: true } },
    },
    ella_cold: {
      id: 'ella_cold',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……뭐가 예쁘다는 거야.',
      nextNodeId: 'zero_scan',
    },
    zero_scan: {
      id: 'zero_scan',
      type: 'dialogue',
      speakerId: 'zero',
      text: '잠깐만, 스캔 좀—— \n……흐음. 겉은 보급형 맞네. 속은 전혀 다른 얘기고.\n당장 완전히 파헤치긴 어려워. 시간이 좀 필요해.',
      nextNodeId: 'yume_ask',
    },
    yume_ask: {
      id: 'yume_ask',
      type: 'dialogue',
      speakerId: 'yume',
      text: '이 장비, 대체 뭐예요?',
      nextNodeId: 'zero_hint',
    },
    zero_hint: {
      id: 'zero_hint',
      type: 'dialogue',
      speakerId: 'zero',
      text: '금지된 실험의 흔적이야. 감정을 연산 자원으로 바꾸는—— 미친 짓이지.\n그리고 너, 엘라.\n피부 아래…… 기계적인 반응이 하나 있어. 사이보그?',
      nextNodeId: 'ella_deny',
      effects: { flags: { cyborg_hint_seen: true }, emotion: { sadness: 15 } },
    },
    ella_deny: {
      id: 'ella_deny',
      type: 'dialogue',
      speakerId: 'ella',
      text: '……그럴 리 없어. 나는—— \n……인간이야.',
      nextNodeId: 'yume_comfort',
    },
    yume_comfort: {
      id: 'yume_comfort',
      type: 'dialogue',
      speakerId: 'yume',
      text: '엘라 씨…… \n인간이든 뭐든, 엘라 씨는 엘라 씨잖아.\n……나는, 옆에 있을게.',
      nextNodeId: 'zero_candy',
      effects: { emotion: { affectionYume: 15, love: 5 } },
    },
    zero_candy: {
      id: 'zero_candy',
      type: 'dialogue',
      speakerId: 'zero',
      text: '뭐, 정체성은 천천히 알아가면 돼. 사탕 하나 먹고——\n다음에 오면, 1차 분석 결과라도 보여줄게. 약속.',
      nextNodeId: 'ch1_close',
    },
    ch1_close: {
      id: 'ch1_close',
      type: 'dialogue',
      speakerId: 'narrator',
      text: '연구실을 나설 때, 엘라의 장비는 여전히 「보급형 v0.3」이라 표시하고 있었다.\n하지만 Sync 게이지는—— 조용히 10%를 넘어섰다.',
      nextNodeId: 'ch1_end',
    },
    ch1_end: {
      id: 'ch1_end',
      type: 'end',
      effects: {
        flags: { ch1_complete: true },
      },
    },
  },
}
